function D = delsq(G)
%DELSQ  Construct five-point finite difference Laplacian.
%   delsq(G) is the sparse form of the two-dimensional,
%   5-point discrete negative Laplacian on the grid G.
%   The grid G can be generated by NUMGRID or NESTED.
%
%   See also NUMGRID, DEL2, DELSQDEMO.

%   C. Moler, 7-16-91.
%   Copyright (c) 1984-98 by The MathWorks, Inc.
%   $Revision: 5.3 $  $Date: 1997/11/21 23:25:31 $

[m,n] = size(G);

% Indices of interior points
% p est un grand vecteur colonne renvoyant les indices des elements
% non-nuls de la matrice G (indices en parcourant colonne par colonne cad
% que 2e ligne; 1e colonne = 2
p = find(G);

% Connect interior points to themselves with 4's.
% i et j sont des vecteurs colonnes avec les éléments non nuls de G
i = G(p);
j = G(p);
s = 4*ones(size(p)); % s est un vecteur colonne de la taille de p donc taille = nb elements non nuls de G et composé que de 4

% for k = north, east, south, west
% G(p-1) renvoie élément au nord donc au dessus de G(p)
% G(p+1) renvoie élément au sud donc en dessous de G(p)
% G(p-m) renvoie élément a l'ouest donc à gauche de G(p)
% G(p+m) renvoie élément a l'est donc à droite de G(p)
% Tout cela du au fait de la numérotation en parcourant les colonnes
for k = [-1 m 1 -m]
   % Possible neighbors in k-th direction
   Q = G(p+k);
   % Index of points with interior neighbors
   q = find(Q); % q sera égal à 1 si G(p+k) non nul et tableau vide si nul
   % Connect interior points to neighbors with -1's.
   i = [i; G(p(q))]; % Si G(p+k) non nul on rajoute à i le 1e element de la matrice G sinon on ne rajoute rien
   j = [j; Q(q)]; % Si G(p+k) non nul on rajoute a j cet element sinon rajoute rien
   s = [s; -ones(length(q),1)]; % Si G(p+k) non nul rajoute -1 a la fin du vecteur contenant que des 4 sinon on ne rajoute rien
end
D = sparse(i,j,s); % Génère une matrice creuse (présence seulement des éléments non nuls et de leurs indices) telle que D(i(k),j(k))=s(k)

